# Generated by Django 3.0.1 on 2019-12-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=16)),
                ('lastname', models.CharField(max_length=16)),
                ('grescore', models.IntegerField()),
                ('toeflscore', models.IntegerField()),
                ('unirating', models.IntegerField()),
                ('sop', models.IntegerField()),
                ('lor', models.IntegerField()),
                ('cgpa', models.IntegerField()),
                ('research', models.IntegerField()),
            ],
        ),
    ]
